package com.chamanotrampo.app;

import android.app.Activity;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.Color;
import android.graphics.Typeface;
import android.graphics.drawable.GradientDrawable;
import android.net.Uri;
import android.os.Bundle;
import android.view.Gravity;
import android.view.View;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.HorizontalScrollView;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;
import android.widget.Toast;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.Locale;

public class MainActivity extends Activity {
    private static final String PREFS="chama_no_trampo_prefs", KEY_OPS="oportunidades_salvas", KEY_CHAT="chat_proposta_", KEY_STATUS="status_conversa_", KEY_AV="avaliacao_proposta_", KEY_FAV="favorito_proposta_", KEY_NOT="notificacoes_internas";
    private static final String KEY_NOME="perfil_nome", KEY_CIDADE="perfil_cidade", KEY_TEL="perfil_telefone", KEY_TIPO="perfil_tipo_usuario";
    private static final String AG="AGUARDANDO_RESPOSTA", EC="EM_CONVERSA", CB="COMBINADO", CL="CONCLUIDO";
    private static final int CREAM=Color.rgb(255,248,239), INK=Color.rgb(43,34,80), LIGHT=Color.rgb(119,110,142), YELLOW=Color.rgb(255,210,63), ORANGE=Color.rgb(255,140,66), RED=Color.rgb(255,92,92), GREEN=Color.rgb(6,193,103), WPP=Color.rgb(31,184,85), BLUE=Color.rgb(61,174,255), PURPLE=Color.rgb(155,93,229), WHITE=Color.WHITE;
    private ArrayList<Oportunidade> ops=new ArrayList<Oportunidade>();
    private LinearLayout lista;
    private String filtro="TODOS", nome="", cidade="", tel="", tipoUsuario="";
    private boolean podeFechar=true;

    @Override protected void onCreate(Bundle b){super.onCreate(b);try{carregarPerfil();carregarOps();home();}catch(Throwable e){erro(e);}}
    @Override public void onBackPressed(){if(podeFechar){super.onBackPressed();}else{home();}}

    private SharedPreferences prefs(){return getSharedPreferences(PREFS,MODE_PRIVATE);}    
    private void carregarPerfil(){SharedPreferences p=prefs();nome=p.getString(KEY_NOME,"");cidade=p.getString(KEY_CIDADE,"");tel=p.getString(KEY_TEL,"");tipoUsuario=p.getString(KEY_TIPO,"");}
    private void salvarPerfil(String n,String c,String t,String tp){nome=n;cidade=c;tel=t;tipoUsuario=tp;prefs().edit().putString(KEY_NOME,nome).putString(KEY_CIDADE,cidade).putString(KEY_TEL,tel).putString(KEY_TIPO,tipoUsuario).apply();}
    private boolean perfilOk(){return nome.trim().length()>0&&tel.trim().length()>0;}

    private void carregarOps(){ops.clear();String s=prefs().getString(KEY_OPS,"");if(s!=null&&s.trim().length()>0){String[] ls=s.split("\\n");for(int i=0;i<ls.length;i++){String[] c=ls[i].split("\\|",-1);if(c.length>=8)ops.add(new Oportunidade(dec(c[0]),dec(c[1]),dec(c[2]),dec(c[3]),dec(c[4]),dec(c[5]),dec(c[6]),dec(c[7])));else if(c.length>=7){Oportunidade o=new Oportunidade("",dec(c[0]),dec(c[1]),dec(c[2]),dec(c[3]),dec(c[4]),dec(c[5]),dec(c[6]));o.id=chaveVelha(o);ops.add(o);}}}if(ops.isEmpty()){ops.add(new Oportunidade(novoId("Auxiliar"),"VAGA","Auxiliar de producao","Guariba - Centro","Salario a combinar","Empresa local buscando inicio imediato.","16999999999","Equipe Chama no Trampo"));ops.add(new Oportunidade(novoId("Pedreiro"),"SERVICO","Pedreiro para reforma","Jardinopolis","Enviar orcamento","Cliente precisa reformar uma area pequena.","16999999999","Equipe Chama no Trampo"));ops.add(new Oportunidade(novoId("Ajudante"),"BICO","Ajudante para descarregar caminhao","Ribeirao Preto","R$ 120,00 no dia","Servico rapido, pagamento no mesmo dia.","16999999999","Equipe Chama no Trampo"));ops.add(new Oportunidade(novoId("Eletricista"),"URGENTE","Eletricista hoje","Jaboticabal","Valor a combinar","Atendimento ainda hoje.","16999999999","Equipe Chama no Trampo"));ops.add(new Oportunidade(novoId("TST"),"SEGURANCA","Tecnico de seguranca do trabalho","Ribeirao Preto e regiao","Enviar pretensao","Acompanhamento de obra e documentacao.","16999999999","Equipe Chama no Trampo"));}}
    private void salvarOps(){StringBuilder b=new StringBuilder();for(int i=0;i<ops.size();i++){Oportunidade o=ops.get(i);if(o.id==null||o.id.trim().length()==0)o.id=chaveVelha(o);b.append(enc(o.id)).append('|').append(enc(o.tipo)).append('|').append(enc(o.titulo)).append('|').append(enc(o.local)).append('|').append(enc(o.valor)).append('|').append(enc(o.desc)).append('|').append(enc(o.contato)).append('|').append(enc(o.autor));if(i<ops.size()-1)b.append('\n');}prefs().edit().putString(KEY_OPS,b.toString()).apply();}

    private void home(){LinearLayout r=base();r.addView(header("Chama no Trampo","Empregos, bicos e servicos perto de voce"));r.addView(sp(12));r.addView(perfilCard());r.addView(sp(12));r.addView(buscaCard());r.addView(sp(8));r.addView(atalhos());r.addView(sp(8));r.addView(chips());r.addView(sp(10));r.addView(txt(contar(filtro)+" oportunidades "+("TODOS".equals(filtro)?"perto de voce":filtro.toLowerCase()),14,LIGHT,true));r.addView(sp(8));lista=col();r.addView(lista);setComNav(scroll(r),"inicio",true);atualizarLista();}
    private View perfilCard(){LinearLayout c=card(WHITE);if(perfilOk()){c.addView(txt("Perfil ativo: "+nome,15,INK,true));c.addView(txt((cidade.length()==0?"Cidade nao informada":cidade)+" - "+(tipoUsuario.length()==0?"Usuario local":tipoUsuario),13,LIGHT,false));}else c.addView(txt("Complete seu perfil para publicar e negociar com mais confianca",14,INK,true));c.setOnClickListener(new View.OnClickListener(){public void onClick(View v){perfil();}});return c;}
    private View buscaCard(){LinearLayout b=row();b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(16),dp(12),dp(16),dp(12));b.setBackground(bg(WHITE,999));b.setElevation(dp(3));b.addView(txt("Buscar: pedreiro, eletricista, cidade...",14,LIGHT,true),new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1));b.setOnClickListener(new View.OnClickListener(){public void onClick(View v){buscar("");}});return b;}
    private View atalhos(){LinearLayout l=row();l.addView(btn("Favoritos",WHITE,INK,new View.OnClickListener(){public void onClick(View v){favoritos();}}),new LinearLayout.LayoutParams(0,dp(44),1));l.addView(wsp(8));l.addView(btn("Avisos internos",WHITE,INK,new View.OnClickListener(){public void onClick(View v){avisos();}}),new LinearLayout.LayoutParams(0,dp(44),1));return l;}
    private View chips(){HorizontalScrollView h=new HorizontalScrollView(this);h.setHorizontalScrollBarEnabled(false);LinearLayout l=row();l.addView(chip("Todos","TODOS"));l.addView(chip("Vagas","VAGA"));l.addView(chip("Bicos","BICO"));l.addView(chip("Servicos","SERVICO"));l.addView(chip("Urgentes","URGENTE"));l.addView(chip("Seguranca","SEGURANCA"));h.addView(l);return h;}
    private TextView chip(String n,final String f){boolean a=f.equals(filtro);TextView c=txt(n,14,a?WHITE:corTipo(f),true);c.setGravity(Gravity.CENTER);c.setPadding(dp(17),dp(9),dp(17),dp(9));c.setBackground(bg(a?INK:tint(f),999));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,dp(42));p.setMargins(0,0,dp(9),0);c.setLayoutParams(p);c.setOnClickListener(new View.OnClickListener(){public void onClick(View v){filtro=f;home();}});return c;}
    private void atualizarLista(){lista.removeAllViews();int t=0;for(int i=0;i<ops.size();i++){Oportunidade o=ops.get(i);if("TODOS".equals(filtro)||o.tipo.equals(filtro)){lista.addView(cardResumoOp(o,"home"));lista.addView(sp(14));t++;}}if(t==0)lista.addView(bloco("Nenhuma oportunidade nesta categoria.",14,LIGHT,false,WHITE,18));}
    private View cardResumoOp(final Oportunidade o,final String origem){LinearLayout c=card(tint(o.tipo));LinearLayout top=row();top.setGravity(Gravity.CENTER_VERTICAL);top.addView(pill(labelTipo(o.tipo),corTipo(o.tipo),Color.argb(105,255,255,255)),new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1));top.addView(txt(fav(o)?"Favorito":dist(o),12,fav(o)?ORANGE:LIGHT,true));c.addView(top);c.addView(sp(8));c.addView(txt(o.titulo,21,INK,true));c.addView(txt(o.local,14,LIGHT,true));c.addView(txt(o.valor.length()==0?"Valor a combinar":o.valor,15,preco(o.valor),true));c.addView(sp(8));c.addView(statusPill(status(o)));c.addView(sp(10));c.addView(btn("Abrir detalhes",INK,WHITE,new View.OnClickListener(){public void onClick(View v){detalhes(o,origem);}}),lp(-1,48));c.setOnClickListener(new View.OnClickListener(){public void onClick(View v){detalhes(o,origem);}});return c;}

    private void detalhes(final Oportunidade o,final String origem){LinearLayout r=base();r.addView(header("Detalhes da oportunidade","Veja tudo antes de conversar."));r.addView(sp(12));LinearLayout c=card(tint(o.tipo));c.addView(pill(labelTipo(o.tipo),corTipo(o.tipo),Color.argb(105,255,255,255)));c.addView(sp(6));c.addView(txt(o.titulo,24,INK,true));c.addView(txt(o.local,15,LIGHT,true));c.addView(txt("por "+autor(o),13,LIGHT,false));c.addView(sp(8));c.addView(txt(o.valor.length()==0?"Valor a combinar":o.valor,16,preco(o.valor),true));c.addView(sp(8));c.addView(txt(o.desc.length()==0?"Sem descricao informada.":o.desc,15,Color.rgb(86,76,114),false));c.addView(sp(10));c.addView(statusPill(status(o)));if(temAv(o)){c.addView(sp(8));c.addView(resumoAv(o));}r.addView(c);r.addView(sp(12));r.addView(btn(fav(o)?"Remover dos favoritos":"Salvar favorito",fav(o)?RED:ORANGE,WHITE,new View.OnClickListener(){public void onClick(View v){toggleFav(o);if("favoritos".equals(origem)&&!fav(o))favoritos();else detalhes(o,origem);}}),lp(-1,48));r.addView(sp(8));r.addView(btn("Abrir conversa",INK,WHITE,new View.OnClickListener(){public void onClick(View v){chat(o);}}),lp(-1,48));r.addView(sp(8));r.addView(btn("Chamar no WhatsApp",WPP,WHITE,new View.OnClickListener(){public void onClick(View v){whats(o);}}),lp(-1,48));r.addView(sp(8));r.addView(btn("Voltar",WHITE,INK,new View.OnClickListener(){public void onClick(View v){voltar(origem);}}),lp(-1,48));setComNav(scroll(r),origem!=null&&origem.startsWith("busca:")?"buscar":"inicio",false);}
    private void voltar(String origem){if("favoritos".equals(origem)){favoritos();return;}if(origem!=null&&origem.startsWith("busca:")){resultadoBusca(origem.substring(6));return;}home();}

    private void buscar(String termo){LinearLayout r=base();r.addView(header("Buscar","Encontre oportunidades pelo texto."));r.addView(sp(12));final EditText e=campo("Digite: pedreiro, eletricista, Ribeirao...");e.setText(termo);r.addView(e);r.addView(sp(10));r.addView(btn("Buscar agora",INK,WHITE,new View.OnClickListener(){public void onClick(View v){resultadoBusca(e.getText().toString().trim());}}),lp(-1,50));r.addView(sp(12));r.addView(txt("Sugestoes rapidas",14,INK,true));r.addView(sp(8));HorizontalScrollView h=new HorizontalScrollView(this);LinearLayout l=row();l.addView(chipBusca("Pedreiro"));l.addView(chipBusca("Eletricista"));l.addView(chipBusca("Ribeirao"));l.addView(chipBusca("Hoje"));l.addView(chipBusca("Seguranca"));h.addView(l);r.addView(h);r.addView(sp(12));r.addView(bloco("A busca procura em titulo, cidade, valor, descricao, autor e categoria.",14,LIGHT,false,WHITE,18));setComNav(scroll(r),"buscar",false);}
    private TextView chipBusca(final String s){TextView c=txt(s,13,INK,true);c.setGravity(Gravity.CENTER);c.setPadding(dp(14),dp(9),dp(14),dp(9));c.setBackground(bg(WHITE,999));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,dp(42));p.setMargins(0,0,dp(8),0);c.setLayoutParams(p);c.setOnClickListener(new View.OnClickListener(){public void onClick(View v){resultadoBusca(s);}});return c;}
    private void resultadoBusca(final String termo){LinearLayout r=base();r.addView(header("Resultado da busca",termo.length()==0?"Mostrando todas.":"Busca por: "+termo));r.addView(sp(12));r.addView(btn("Nova busca",WHITE,INK,new View.OnClickListener(){public void onClick(View v){buscar(termo);}}),lp(-1,46));r.addView(sp(12));int total=0;for(int i=0;i<ops.size();i++){Oportunidade o=ops.get(i);if(termo.length()==0||match(o,termo)){r.addView(cardResumoOp(o,"busca:"+termo));r.addView(sp(12));total++;}}if(total==0)r.addView(bloco("Nenhuma oportunidade encontrada.",14,LIGHT,false,WHITE,18));setComNav(scroll(r),"buscar",false);}
    private boolean match(Oportunidade o,String t){return (o.tipo+" "+o.titulo+" "+o.local+" "+o.valor+" "+o.desc+" "+o.autor).toLowerCase().contains(t.toLowerCase());}

    private void favoritos(){LinearLayout r=base();r.addView(header("Favoritos","Oportunidades salvas neste aparelho."));r.addView(sp(12));int total=0;for(int i=0;i<ops.size();i++)if(fav(ops.get(i))){r.addView(cardResumoOp(ops.get(i),"favoritos"));r.addView(sp(12));total++;}if(total==0)r.addView(bloco("Nenhum favorito salvo ainda. Abra uma oportunidade e toque em Salvar favorito.",14,LIGHT,false,WHITE,18));r.addView(sp(10));r.addView(btn("Voltar",WHITE,INK,new View.OnClickListener(){public void onClick(View v){home();}}),lp(-1,48));setComNav(scroll(r),"inicio",false);}
    private boolean fav(Oportunidade o){return prefs().getBoolean(KEY_FAV+chave(o),false);} private void toggleFav(Oportunidade o){boolean n=!fav(o);prefs().edit().putBoolean(KEY_FAV+chave(o),n).apply();not(n?"Favorito salvo":"Favorito removido",o.titulo);Toast.makeText(this,n?"Salvo nos favoritos.":"Removido dos favoritos.",Toast.LENGTH_SHORT).show();}

    private void avisos(){LinearLayout r=base();r.addView(header("Avisos internos","Historico local do que aconteceu no app."));r.addView(sp(12));r.addView(bloco("Estes avisos ficam apenas dentro do app. Ainda nao sao notificacoes push do Android.",13,LIGHT,false,WHITE,18));r.addView(sp(12));ArrayList<Notificacao> ns=notificacoes();if(ns.isEmpty())r.addView(bloco("Nenhum aviso interno ainda.",14,LIGHT,false,WHITE,18));else for(int i=ns.size()-1;i>=0;i--){r.addView(cardNot(ns.get(i)));r.addView(sp(8));}r.addView(sp(10));r.addView(btn("Limpar avisos internos",RED,WHITE,new View.OnClickListener(){public void onClick(View v){prefs().edit().remove(KEY_NOT).apply();avisos();}}),lp(-1,48));r.addView(sp(10));r.addView(btn("Voltar",WHITE,INK,new View.OnClickListener(){public void onClick(View v){home();}}),lp(-1,48));setComNav(scroll(r),"inicio",false);}
    private View cardNot(Notificacao n){LinearLayout c=card(WHITE);c.addView(txt(n.titulo,16,INK,true));c.addView(txt(n.texto,13,LIGHT,false));c.addView(txt(n.data,11,LIGHT,false));return c;}
    private void not(String titulo,String texto){ArrayList<Notificacao> ns=notificacoes();ns.add(new Notificacao(titulo,texto,agora()));while(ns.size()>30)ns.remove(0);StringBuilder b=new StringBuilder();for(int i=0;i<ns.size();i++){Notificacao n=ns.get(i);b.append(enc(n.titulo)).append('|').append(enc(n.texto)).append('|').append(enc(n.data));if(i<ns.size()-1)b.append('\n');}prefs().edit().putString(KEY_NOT,b.toString()).apply();}
    private ArrayList<Notificacao> notificacoes(){ArrayList<Notificacao> ns=new ArrayList<Notificacao>();String s=prefs().getString(KEY_NOT,"");if(s==null||s.trim().length()==0)return ns;String[] ls=s.split("\\n");for(int i=0;i<ls.length;i++){String[] c=ls[i].split("\\|",-1);if(c.length>=3)ns.add(new Notificacao(dec(c[0]),dec(c[1]),dec(c[2])));}return ns;}

    private void chat(final Oportunidade o){LinearLayout r=base();r.addView(header("Conversa da proposta","Negocie dentro do app; WhatsApp fica como saida final."));r.addView(sp(12));r.addView(cardMini(o));r.addView(sp(10));r.addView(statusBox(o));if(temAv(o)){r.addView(sp(10));r.addView(resumoAv(o));}else if(CL.equals(status(o))){r.addView(sp(10));r.addView(chamadaAv(o));}r.addView(sp(12));ArrayList<Mensagem> ms=msgs(o);if(ms.isEmpty())r.addView(bloco("Nenhuma mensagem ainda.",14,LIGHT,false,WHITE,18));for(int i=0;i<ms.size();i++){r.addView(msgCard(ms.get(i)));r.addView(sp(8));}r.addView(sp(12));r.addView(txt("Mensagens rapidas",14,INK,true));r.addView(sp(6));r.addView(rapidas(o));r.addView(sp(12));final EditText e=campo("Digite sua mensagem...");e.setMinLines(1);e.setMaxLines(4);r.addView(e);r.addView(sp(10));r.addView(btn("Enviar mensagem",INK,WHITE,new View.OnClickListener(){public void onClick(View v){String t=e.getText().toString().trim();if(t.length()==0){Toast.makeText(MainActivity.this,"Digite uma mensagem.",Toast.LENGTH_SHORT).show();return;}addMsg(o,"Voce",t,"texto");not("Mensagem registrada",o.titulo);if(AG.equals(status(o)))setStatus(o,EC);chat(o);}}),lp(-1,50));r.addView(sp(10));r.addView(statusBtns(o));r.addView(sp(10));r.addView(btn("Continuar pelo WhatsApp",WPP,WHITE,new View.OnClickListener(){public void onClick(View v){whats(o);}}),lp(-1,48));r.addView(sp(10));r.addView(btn("Voltar aos detalhes",WHITE,INK,new View.OnClickListener(){public void onClick(View v){detalhes(o,"home");}}),lp(-1,48));setComNav(scroll(r),"chat",false);}
    private View cardMini(Oportunidade o){LinearLayout c=card(tint(o.tipo));c.addView(txt(o.titulo,20,INK,true));c.addView(txt(o.local,14,LIGHT,true));c.addView(txt(o.valor.length()==0?"Valor a combinar":o.valor,14,preco(o.valor),true));c.addView(txt("Proposta -> Conversa -> Combinado -> Concluido -> Avaliacao",12,LIGHT,false));return c;}
    private View statusBox(Oportunidade o){LinearLayout b=row();b.setGravity(Gravity.CENTER_VERTICAL);b.setPadding(dp(14),dp(12),dp(14),dp(12));b.setBackground(bg(WHITE,18));b.setElevation(dp(2));b.addView(txt("Status",14,LIGHT,true),new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1));b.addView(statusPill(status(o)));return b;}
    private View chamadaAv(final Oportunidade o){LinearLayout b=card(WHITE);b.addView(txt("Servico concluido",17,INK,true));b.addView(txt("Avalie a experiencia para registrar o historico local.",13,LIGHT,false));b.addView(sp(8));b.addView(btn("Avaliar servico",ORANGE,WHITE,new View.OnClickListener(){public void onClick(View v){avaliar(o);}}),lp(-1,46));return b;}
    private View msgCard(Mensagem m){boolean minha="Voce".equals(m.autor);LinearLayout linha=row();linha.setGravity(minha?Gravity.RIGHT:Gravity.LEFT);LinearLayout b=col();b.setPadding(dp(14),dp(10),dp(14),dp(10));b.setBackground(bg(minha?INK:WHITE,18));b.setElevation(dp(1));b.addView(txt(m.autor+" - "+m.hora,11,minha?Color.rgb(220,214,236):LIGHT,true));b.addView(txt(m.texto,15,minha?WHITE:INK,false));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,LinearLayout.LayoutParams.WRAP_CONTENT);p.setMargins(minha?dp(44):0,0,minha?0:dp(44),0);linha.addView(b,p);return linha;}
    private View rapidas(final Oportunidade o){HorizontalScrollView h=new HorizontalScrollView(this);h.setHorizontalScrollBarEnabled(false);LinearLayout l=row();l.addView(rapida(o,"Qual melhor horario?"));l.addView(rapida(o,"Consegue fazer por esse valor?"));l.addView(rapida(o,"Pode me mandar o endereco?"));l.addView(rapida(o,"Servico combinado"));h.addView(l);return h;}
    private TextView rapida(final Oportunidade o,final String m){TextView c=txt(m,13,INK,true);c.setGravity(Gravity.CENTER);c.setPadding(dp(14),dp(9),dp(14),dp(9));c.setBackground(bg(WHITE,999));LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(LinearLayout.LayoutParams.WRAP_CONTENT,dp(42));p.setMargins(0,0,dp(8),0);c.setLayoutParams(p);c.setOnClickListener(new View.OnClickListener(){public void onClick(View v){addMsg(o,"Voce",m,"rapida");setStatus(o,"Servico combinado".equals(m)?CB:EC);not("Mensagem rapida",m);chat(o);}});return c;}
    private View statusBtns(final Oportunidade o){LinearLayout b=col();if(!CL.equals(status(o))){b.addView(btn("Marcar como combinado",GREEN,WHITE,new View.OnClickListener(){public void onClick(View v){setStatus(o,CB);addMsg(o,"Sistema","Servico combinado.","status");not("Servico combinado",o.titulo);chat(o);}}),lp(-1,48));b.addView(sp(8));b.addView(btn("Concluir servico",Color.rgb(93,93,112),WHITE,new View.OnClickListener(){public void onClick(View v){setStatus(o,CL);addMsg(o,"Sistema","Servico concluido.","status");not("Servico concluido",o.titulo);avaliar(o);}}),lp(-1,48));}else b.addView(btn(temAv(o)?"Editar avaliacao":"Avaliar servico",ORANGE,WHITE,new View.OnClickListener(){public void onClick(View v){avaliar(o);}}),lp(-1,48));return b;}

    private void avaliar(final Oportunidade o){LinearLayout r=base();r.addView(header("Avaliar servico","Salve uma nota local apos a conclusao."));r.addView(sp(12));r.addView(cardMini(o));r.addView(sp(12));Avaliacao av=av(o);final int[] nota=new int[]{av.nota};final TextView label=txt("Nota selecionada: "+(nota[0]<=0?"nenhuma":nota[0]+"/5"),16,INK,true);r.addView(label);r.addView(sp(8));LinearLayout ns=row();for(int i=1;i<=5;i++){final int v=i;TextView bt=txt(String.valueOf(i),18,INK,true);bt.setGravity(Gravity.CENTER);bt.setBackground(bg(WHITE,999));bt.setOnClickListener(new View.OnClickListener(){public void onClick(View x){nota[0]=v;label.setText("Nota selecionada: "+v+"/5");}});LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(0,dp(48),1);p.setMargins(0,0,dp(7),0);ns.addView(bt,p);}r.addView(ns);r.addView(sp(12));final EditText com=campo("Comentario sobre o servico");com.setMinLines(3);com.setMaxLines(6);if(av.com.length()>0)com.setText(av.com);r.addView(com);r.addView(sp(12));r.addView(btn("Salvar avaliacao",GREEN,WHITE,new View.OnClickListener(){public void onClick(View v){if(nota[0]<=0){Toast.makeText(MainActivity.this,"Escolha uma nota de 1 a 5.",Toast.LENGTH_SHORT).show();return;}salvarAv(o,nota[0],com.getText().toString().trim());addMsg(o,"Sistema","Avaliacao salva: "+nota[0]+"/5.","avaliacao");not("Avaliacao salva",o.titulo+" - "+nota[0]+"/5");Toast.makeText(MainActivity.this,"Avaliacao salva no aparelho.",Toast.LENGTH_LONG).show();chat(o);}}),lp(-1,50));r.addView(sp(10));r.addView(btn("Voltar para conversa",WHITE,INK,new View.OnClickListener(){public void onClick(View v){chat(o);}}),lp(-1,48));setComNav(scroll(r),"chat",false);}
    private View resumoAv(Oportunidade o){Avaliacao a=av(o);LinearLayout b=col();b.setPadding(dp(13),dp(10),dp(13),dp(10));b.setBackground(bg(Color.argb(145,255,255,255),16));b.addView(txt("Avaliacao: "+a.nota+"/5",14,ORANGE,true));if(a.com.length()>0)b.addView(txt(a.com,13,LIGHT,false));if(a.data.length()>0)b.addView(txt("Salva em "+a.data,11,LIGHT,false));return b;}
    private Avaliacao av(Oportunidade o){String s=prefs().getString(KEY_AV+chave(o),"");if(s==null||s.trim().length()==0)return new Avaliacao(0,"","");String[] c=s.split("\\|",-1);int n=0;try{n=Integer.parseInt(c[0]);}catch(Exception e){n=0;}return new Avaliacao(n,c.length>1?dec(c[1]):"",c.length>2?dec(c[2]):"");}
    private void salvarAv(Oportunidade o,int n,String com){prefs().edit().putString(KEY_AV+chave(o),n+"|"+enc(com)+"|"+enc(agora())).apply();}
    private boolean temAv(Oportunidade o){return av(o).nota>0;}

    private void conversas(){LinearLayout r=base();r.addView(header("Conversas","Acompanhe negociacoes locais por proposta."));r.addView(sp(12));int t=0;for(int i=0;i<ops.size();i++)if(temConversa(ops.get(i))){r.addView(convCard(ops.get(i)));r.addView(sp(10));t++;}if(t==0){r.addView(bloco("Voce ainda nao tem conversas iniciadas.",14,LIGHT,false,WHITE,18));r.addView(sp(12));r.addView(txt("Propostas disponiveis",14,INK,true));r.addView(sp(8));for(int i=0;i<ops.size();i++){r.addView(convCard(ops.get(i)));r.addView(sp(10));}}setComNav(scroll(r),"chat",false);}
    private View convCard(final Oportunidade o){LinearLayout c=card(WHITE);LinearLayout top=row();top.setGravity(Gravity.CENTER_VERTICAL);top.addView(txt(o.titulo,17,INK,true),new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.WRAP_CONTENT,1));top.addView(statusPill(status(o)));c.addView(top);c.addView(txt(o.local,13,LIGHT,false));String u=ultima(o);c.addView(txt(u.length()==0?"Toque para iniciar a negociacao local.":u,13,LIGHT,false));if(temAv(o))c.addView(txt("Avaliacao: "+av(o).nota+"/5",12,ORANGE,true));c.setOnClickListener(new View.OnClickListener(){public void onClick(View v){chat(o);}});return c;}
    private boolean temConversa(Oportunidade o){return msgs(o).size()>0||!AG.equals(status(o))||temAv(o);}    
    private ArrayList<Mensagem> msgs(Oportunidade o){ArrayList<Mensagem> ms=new ArrayList<Mensagem>();String s=prefs().getString(KEY_CHAT+chave(o),"");if(s==null||s.trim().length()==0)return ms;String[] ls=s.split("\\n");for(int i=0;i<ls.length;i++){String[] c=ls[i].split("\\|",-1);if(c.length>=4)ms.add(new Mensagem(dec(c[0]),dec(c[1]),dec(c[2]),dec(c[3])));}return ms;}
    private void addMsg(Oportunidade o,String au,String tx,String tp){ArrayList<Mensagem> ms=msgs(o);ms.add(new Mensagem(au,tx,agora(),tp));StringBuilder b=new StringBuilder();for(int i=0;i<ms.size();i++){Mensagem m=ms.get(i);b.append(enc(m.autor)).append('|').append(enc(m.texto)).append('|').append(enc(m.hora)).append('|').append(enc(m.tipo));if(i<ms.size()-1)b.append('\n');}prefs().edit().putString(KEY_CHAT+chave(o),b.toString()).apply();}
    private String ultima(Oportunidade o){ArrayList<Mensagem> ms=msgs(o);if(ms.isEmpty())return "";Mensagem m=ms.get(ms.size()-1);String t=m.autor+": "+m.texto;return t.length()>82?t.substring(0,82)+"...":t;}
    private String status(Oportunidade o){String s=prefs().getString(KEY_STATUS+chave(o),"");if(s==null||s.trim().length()==0)return msgs(o).isEmpty()?AG:EC;return s;}
    private void setStatus(Oportunidade o,String s){prefs().edit().putString(KEY_STATUS+chave(o),s).apply();}
    private String chave(Oportunidade o){return o.id!=null&&o.id.trim().length()>0?o.id:chaveVelha(o);} private String chaveVelha(Oportunidade o){return String.valueOf(Math.abs((o.titulo+"|"+o.local+"|"+o.autor+"|"+o.contato).hashCode()));} private String novoId(String base){return "local_"+System.currentTimeMillis()+"_"+Math.abs(base.hashCode());}

    private TextView statusPill(String s){return pill(labelStatus(s),corStatus(s),fundoStatus(s));}
    private TextView pill(String s,int cor,int fundo){TextView v=txt(s,12,cor,true);v.setGravity(Gravity.CENTER);v.setPadding(dp(10),dp(5),dp(10),dp(5));v.setBackground(bg(fundo,999));return v;}
    private String labelStatus(String s){if(EC.equals(s))return "Em conversa";if(CB.equals(s))return "Combinado";if(CL.equals(s))return "Concluido";return "Aguardando resposta";} private int corStatus(String s){if(EC.equals(s))return BLUE;if(CB.equals(s))return GREEN;if(CL.equals(s))return Color.rgb(80,80,94);return ORANGE;} private int fundoStatus(String s){if(EC.equals(s))return Color.rgb(238,244,255);if(CB.equals(s))return Color.rgb(226,252,240);if(CL.equals(s))return Color.rgb(238,238,242);return Color.rgb(255,241,214);}

    private void publicar(){LinearLayout r=base();r.addView(header("Publicar oportunidade","Cadastre uma vaga, bico ou servico."));r.addView(sp(12));if(!perfilOk()){r.addView(bloco("Dica: cadastre seu perfil antes de publicar.",14,WHITE,true,ORANGE,18));r.addView(sp(10));}final EditText tp=campo("Tipo: VAGA, BICO, SERVICO, URGENTE ou SEGURANCA"), ti=campo("Titulo"), ci=campo("Cidade / bairro"), va=campo("Valor ou salario"), de=campo("Descricao"), co=campo("WhatsApp");if(tel.length()>0)co.setText(tel);if(cidade.length()>0)ci.setText(cidade);r.addView(tp);r.addView(sp(8));r.addView(ti);r.addView(sp(8));r.addView(ci);r.addView(sp(8));r.addView(va);r.addView(sp(8));r.addView(de);r.addView(sp(8));r.addView(co);r.addView(sp(14));r.addView(btn("Salvar oportunidade",GREEN,WHITE,new View.OnClickListener(){public void onClick(View v){String a=tp.getText().toString().trim().toUpperCase(),b=ti.getText().toString().trim(),c=ci.getText().toString().trim(),d=va.getText().toString().trim(),e=de.getText().toString().trim(),f=co.getText().toString().trim();if(a.length()==0)a="BICO";if(b.length()==0||c.length()==0||f.length()==0){Toast.makeText(MainActivity.this,"Preencha titulo, cidade e contato.",Toast.LENGTH_LONG).show();return;}ops.add(0,new Oportunidade(novoId(b),a,b,c,d,e,f,nome.length()==0?"Usuario local":nome));salvarOps();filtro="TODOS";not("Oportunidade publicada",b);Toast.makeText(MainActivity.this,"Oportunidade salva neste aparelho.",Toast.LENGTH_LONG).show();home();}}),lp(-1,50));r.addView(sp(10));r.addView(btn("Voltar",WHITE,INK,new View.OnClickListener(){public void onClick(View v){home();}}),lp(-1,48));setComNav(scroll(r),"publicar",false);}
    private void perfil(){LinearLayout r=base();r.addView(header("Meu perfil","Crie uma identidade para publicar."));r.addView(sp(12));final EditText n=campo("Seu nome ou empresa"),c=campo("Cidade / bairro"),t=campo("WhatsApp"),tp=campo("Tipo: Trabalhador, Contratante, Empresa ou Autonomo");n.setText(nome);c.setText(cidade);t.setText(tel);tp.setText(tipoUsuario);r.addView(n);r.addView(sp(8));r.addView(c);r.addView(sp(8));r.addView(t);r.addView(sp(8));r.addView(tp);r.addView(sp(14));r.addView(btn("Salvar perfil",GREEN,WHITE,new View.OnClickListener(){public void onClick(View v){String nn=n.getText().toString().trim(),cc=c.getText().toString().trim(),tt=t.getText().toString().trim(),ttpp=tp.getText().toString().trim();if(nn.length()==0||tt.length()==0){Toast.makeText(MainActivity.this,"Preencha pelo menos nome e WhatsApp.",Toast.LENGTH_LONG).show();return;}salvarPerfil(nn,cc,tt,ttpp.length()==0?"Usuario local":ttpp);not("Perfil atualizado",nn);Toast.makeText(MainActivity.this,"Perfil salvo.",Toast.LENGTH_LONG).show();home();}}),lp(-1,50));r.addView(sp(10));r.addView(btn("Meus favoritos",ORANGE,WHITE,new View.OnClickListener(){public void onClick(View v){favoritos();}}),lp(-1,48));r.addView(sp(8));r.addView(btn("Avisos internos",INK,WHITE,new View.OnClickListener(){public void onClick(View v){avisos();}}),lp(-1,48));r.addView(sp(10));r.addView(bloco("Dados ficam salvos neste aparelho ate entrar Firebase.",14,LIGHT,false,WHITE,18));r.addView(sp(10));r.addView(btn("Voltar",WHITE,INK,new View.OnClickListener(){public void onClick(View v){home();}}),lp(-1,48));setComNav(scroll(r),"perfil",false);}

    private View header(String t,String s){LinearLayout h=col();h.setGravity(Gravity.CENTER_VERTICAL);h.setPadding(dp(20),dp(18),dp(20),dp(18));h.setBackground(grad(YELLOW,ORANGE,28));h.setElevation(dp(4));h.addView(txt(t,26,INK,true));h.addView(txt(s,15,Color.rgb(91,62,30),true));return h;}
    private void setComNav(View content,String ativo,boolean fab){podeFechar=fab;FrameLayout root=new FrameLayout(this);root.setBackgroundColor(CREAM);root.addView(content,new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT,FrameLayout.LayoutParams.MATCH_PARENT));FrameLayout.LayoutParams np=new FrameLayout.LayoutParams(FrameLayout.LayoutParams.MATCH_PARENT,dp(72),Gravity.BOTTOM);root.addView(nav(ativo),np);if(fab){TextView f=txt("+",30,WHITE,true);f.setGravity(Gravity.CENTER);f.setBackground(bg(RED,999));f.setElevation(dp(8));f.setOnClickListener(new View.OnClickListener(){public void onClick(View v){publicar();}});FrameLayout.LayoutParams fp=new FrameLayout.LayoutParams(dp(58),dp(58),Gravity.BOTTOM|Gravity.CENTER_HORIZONTAL);fp.setMargins(0,0,0,dp(42));root.addView(f,fp);}setContentView(root);}
    private LinearLayout nav(String ativo){LinearLayout n=row();n.setGravity(Gravity.CENTER);n.setPadding(dp(14),dp(6),dp(14),dp(6));n.setBackgroundColor(WHITE);n.setElevation(dp(8));n.addView(navItem("Inicio","inicio",ativo,new View.OnClickListener(){public void onClick(View v){filtro="TODOS";home();}}),navLp());n.addView(navItem("Buscar","buscar",ativo,new View.OnClickListener(){public void onClick(View v){buscar("");}}),navLp());n.addView(new TextView(this),navLp());n.addView(navItem("Chat","chat",ativo,new View.OnClickListener(){public void onClick(View v){conversas();}}),navLp());n.addView(navItem("Perfil","perfil",ativo,new View.OnClickListener(){public void onClick(View v){perfil();}}),navLp());return n;}
    private TextView navItem(String t,String k,String a,View.OnClickListener l){TextView v=txt(t,11,k.equals(a)?INK:LIGHT,true);v.setGravity(Gravity.CENTER);v.setBackground(k.equals(a)?bg(Color.rgb(255,241,214),18):bg(Color.TRANSPARENT,18));v.setOnClickListener(l);return v;}

    private void whats(Oportunidade o){String n=limpar(o.contato);if(n.length()==0){Toast.makeText(this,"Contato nao informado.",Toast.LENGTH_LONG).show();return;}String m="Ola, vi sua oportunidade no Chama no Trampo e tenho interesse.\n\nOportunidade: "+o.titulo+"\nLocal: "+o.local;try{String base="http"+"s://wa"+"."+"me/";startActivity(new Intent(Intent.ACTION_VIEW,Uri.parse(base+n+"?text="+Uri.encode(m))));}catch(Exception e){Toast.makeText(this,"Nao consegui abrir o WhatsApp.",Toast.LENGTH_LONG).show();}}
    private String limpar(String c){StringBuilder n=new StringBuilder();for(int i=0;i<c.length();i++){char x=c.charAt(i);if(x>='0'&&x<='9')n.append(x);}String s=n.toString();return(s.length()==10||s.length()==11)?"55"+s:s;}
    private int contar(String f){int t=0;for(int i=0;i<ops.size();i++)if("TODOS".equals(f)||ops.get(i).tipo.equals(f))t++;return t;} private String autor(Oportunidade o){return o.autor==null||o.autor.trim().length()==0?"Usuario local":o.autor;} private String agora(){return new SimpleDateFormat("dd/MM HH:mm",new Locale("pt","BR")).format(new Date());}
    private int tint(String t){if("URGENTE".equals(t))return Color.rgb(255,234,234);if("SERVICO".equals(t))return Color.rgb(230,244,255);if("BICO".equals(t))return Color.rgb(243,234,254);if("SEGURANCA".equals(t))return Color.rgb(255,241,214);return Color.rgb(227,251,240);} private int corTipo(String t){if("URGENTE".equals(t))return RED;if("SERVICO".equals(t))return BLUE;if("BICO".equals(t))return PURPLE;if("SEGURANCA".equals(t))return ORANGE;return GREEN;} private String labelTipo(String t){if("SERVICO".equals(t))return"SERVICO";if("BICO".equals(t))return"BICO";if("URGENTE".equals(t))return"URGENTE";if("SEGURANCA".equals(t))return"SEGURANCA";return"VAGA";} private int preco(String v){return v!=null&&v.contains("R$")?Color.rgb(10,138,77):LIGHT;} private String dist(Oportunidade o){int n=Math.abs((o.titulo+o.local).hashCode())%48;return(n<3?n+1:n)+" km";}
    private String enc(String t){return t==null?"":Uri.encode(t);} private String dec(String t){return t==null?"":Uri.decode(t);}
    private LinearLayout base(){LinearLayout l=col();l.setPadding(dp(18),dp(18),dp(18),dp(128));return l;} private ScrollView scroll(View v){ScrollView s=new ScrollView(this);s.setBackgroundColor(CREAM);s.addView(v);return s;} private LinearLayout col(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);return l;} private LinearLayout row(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.HORIZONTAL);return l;} private LinearLayout card(int cor){LinearLayout l=col();l.setPadding(dp(18),dp(16),dp(18),dp(18));l.setBackground(bg(cor,24));l.setElevation(dp(3));return l;} private EditText campo(String d){EditText e=new EditText(this);e.setHint(d);e.setTextSize(15);e.setSingleLine(false);e.setPadding(dp(14),dp(12),dp(14),dp(12));e.setBackground(bg(WHITE,18));e.setTextColor(INK);e.setHintTextColor(LIGHT);return e;} private TextView btn(String t,int fundo,int cor,View.OnClickListener l){TextView v=bloco(t,15,cor,true,fundo,999);v.setGravity(Gravity.CENTER);v.setOnClickListener(l);v.setElevation(dp(2));return v;} private TextView bloco(String t,int tam,int cor,boolean bold,int fundo,int raio){TextView v=txt(t,tam,cor,bold);v.setPadding(dp(16),dp(13),dp(16),dp(13));v.setBackground(bg(fundo,raio));return v;} private TextView txt(String t,int tam,int cor,boolean bold){TextView v=new TextView(this);v.setText(t);v.setTextSize(tam);v.setTextColor(cor);v.setPadding(0,dp(3),0,dp(3));if(bold)v.setTypeface(Typeface.DEFAULT,Typeface.BOLD);return v;} private GradientDrawable bg(int cor,int raio){GradientDrawable d=new GradientDrawable();d.setColor(cor);d.setCornerRadius(dp(raio));return d;} private GradientDrawable grad(int a,int b,int raio){GradientDrawable d=new GradientDrawable(GradientDrawable.Orientation.LEFT_RIGHT,new int[]{a,b});d.setCornerRadius(dp(raio));return d;} private LinearLayout.LayoutParams lp(int w,int h){int ww=w==-1?LinearLayout.LayoutParams.MATCH_PARENT:w;return new LinearLayout.LayoutParams(ww,dp(h));} private LinearLayout.LayoutParams navLp(){return new LinearLayout.LayoutParams(0,LinearLayout.LayoutParams.MATCH_PARENT,1);} private View sp(int h){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(1,dp(h)));return v;} private View wsp(int w){View v=new View(this);v.setLayoutParams(new LinearLayout.LayoutParams(dp(w),1));return v;} private int dp(int v){return(int)(v*getResources().getDisplayMetrics().density+0.5f);} private void erro(Throwable e){TextView v=new TextView(this);v.setText("Chama no Trampo\n\nErro na tela.\n\n"+e.getClass().getSimpleName()+"\n"+e.getMessage());v.setTextSize(18);v.setTextColor(WHITE);v.setBackgroundColor(Color.rgb(127,29,29));v.setGravity(Gravity.CENTER);v.setPadding(dp(24),dp(24),dp(24),dp(24));setContentView(v);}    

    private static class Oportunidade{String id,tipo,titulo,local,valor,desc,contato,autor;Oportunidade(String id,String tipo,String titulo,String local,String valor,String desc,String contato,String autor){this.id=id;this.tipo=tipo;this.titulo=titulo;this.local=local;this.valor=valor;this.desc=desc;this.contato=contato;this.autor=autor;}}
    private static class Mensagem{String autor,texto,hora,tipo;Mensagem(String a,String t,String h,String p){autor=a;texto=t;hora=h;tipo=p;}}
    private static class Avaliacao{int nota;String com,data;Avaliacao(int n,String c,String d){nota=n;com=c;data=d;}}
    private static class Notificacao{String titulo,texto,data;Notificacao(String t,String x,String d){titulo=t;texto=x;data=d;}}
}
